### PR TITLE
Add table pagination

### PR DESCRIPTION
**Pull request by ed-morgan**
Add table pagination functionality.  Changing the page, rows per page, or the search filter will reset the moreInformation pane back to default.

Refs: #7

### CODE REVIEW

**Comment by ed-morgan** [comment]
Added table pagination to the bottom of the table. Picture at bottom for reference. Changing the rows per page, page, or changing the search filter will reset the more information back to the default of hidden, in case you change onto a page where the expanded patent no longer exists which would cause errors.

Updated "MoreInformation" method name to follow the naming convention of camelCase. 

image

**Comment by al-v-in** [comment]
Looks good!

For the total count for pagination that would need to come from neo4j-graphql-js I think. I'll ask Michael about it.

One extra thing that comes to mind for the pagination is having the current pagination state in the query vars, e.g. /patents?page=2&rows=5, is that something you could take a look at?

**Review by al-v-in — CHANGES_REQUESTED** [review]
Query vars to be added

**Comment by ed-morgan** [comment]
Added URL query params. React.useEffect() loads the initial params on first load or on refresh, so that the values don't get out of sync if you were to refresh the page after being on page 5, rows per page 25 for example.

**Comment by ed-morgan** [comment]
Some screenshots of url query params. Clicking refresh on any page will lead to default table pagination query params (currently set as 0 page, 10 rows per page)

1. Initial Load of patent table (Currently at "/" path)
image

2. Viewing 11-20 (page 2) of 10 rows per page
image

3. Viewing 1-25 (page 1) of 25 rows per page
image

4. Viewing 16-20 (page 4) of 5 rows per page
image

**Review by al-v-in — CHANGES_REQUESTED** [review]
I know you mentioned about it working on refresh but it doesn't seem to be working for me. For example if I manually change the page number in URL it then goes back to zero by itself. Can you duplicate that?

Also please can we have the page numbers starting at 1.

**Comment by ed-morgan** [comment]
Page now starts at 1 (in the url query params). Altering the param values in the url and refreshing will now alter the table pagination. 

Checks to see if page / rowsPerPage have valid numeric values and sets them. If not it uses the default values (page=1 and rowsPerPage=10). If no values are provided then it sets them to these default values too.

**Pull request merged**
